# Generated by Django 3.2.8 on 2021-11-03 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreading',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
