# Generated by Django 3.2.8 on 2021-11-03 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchro', '0002_alter_stockreading_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreading',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
